eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product-view-service-ribbon
  thymeleaf:
    #<!-- 关闭thymeleaf缓存 开发时使用 否则没有实时画面-->
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    #模板编码
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
    ## 检查模板是否存在，然后再呈现
    check-template-location: true
    #启用MVC Thymeleaf视图分辨率
    enabled: true
    ## 应该从解决方案中排除的视图名称的逗号分隔列表
    ##excluded-view-names:
    # 链中模板解析器的顺序
    #template-resolver-order: o
    # 可以解析的视图名称的逗号分隔列表
    #view-names:
    #thymeleaf end